/* KPSS 2026 — Çalışma Motoru: akıllı günlük hedef, odak oturumu, tekrar kuyruğu, başarılar */
(function(){
  'use strict';
  const KEY='kpss_focus_hub_v1';
  const defaultHub=()=>({sessions:[],achievements:{},customDaily:{date:null,done:0,target:1},focus:{minutes:25,break:5},profile:'Ahmet'});
  let HUB={...defaultHub(),...(JSON.parse(localStorage.getItem(KEY)||'null')||{})};
  HUB.sessions=Array.isArray(HUB.sessions)?HUB.sessions:[]; HUB.achievements=HUB.achievements||{};
  const save=()=>localStorage.setItem(KEY,JSON.stringify(HUB));
  const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
  const today=()=>bugunStr();
  function daily(){const d=today();if(HUB.customDaily.date!==d)HUB.customDaily={date:d,done:0,target:1};return HUB.customDaily;}
  function allTopics(){return typeof calismaKonulariniGetir==='function'?calismaKonulariniGetir():[];}
  function weakTopics(){return allTopics().filter(k=>(k.soru||0)>=3).sort((a,b)=>{const ba=yuzde(b.yanlis||0,(b.dogru||0)+(b.yanlis||0));const aa=yuzde(a.yanlis||0,(a.dogru||0)+(a.yanlis||0));return ba-aa||(b.soru||0)-(a.soru||0)}).slice(0,5)}
  function reviewTopics(){return allTopics().filter(k=>k.durum==='tekrar'||((k.soru||0)>=5&&yuzde(k.dogru||0,(k.dogru||0)+(k.yanlis||0))<70)).sort((a,b)=>(a.durum==='tekrar'?0:1)-(b.durum==='tekrar'?0:1));}
  function streak(){let n=0,d=new Date();while(true){const s=bugunStr(d),r=STATE.gunlukKayitlar[s];if(!r||(r.calismaDk<=0&&r.soru<=0))break;n++;d.setDate(d.getDate()-1);if(n>365)break}return n;}
  function addAchievement(id,label){if(HUB.achievements[id])return;HUB.achievements[id]={date:today(),label};save();if(typeof toast==='function')toast('🏆 '+label)}
  function checkAchievements(){const total=genelToplamSoru();if(total>=100)addAchievement('100s','100 soru tamamlandı');if(total>=500)addAchievement('500s','500 soru tamamlandı');if(genelToplamCalismaDk()>=300)addAchievement('5h','Toplam 5 saat çalışma');if(streak()>=3)addAchievement('3day','3 günlük seri');if(streak()>=7)addAchievement('7day','7 günlük seri');if(allTopics().filter(k=>k.durum==='tamamlandi').length>=10)addAchievement('10topic','10 konu tamamlandı');}
  function renderHub(){const page=document.querySelector('#page-calisma');if(!page)return;const d=daily(),topics=allTopics(),review=reviewTopics(),weak=weakTopics(),dk=gunlukKayitAl().calismaDk||0,soru=gunlukKayitAl().soru||0,hedefDk=STATE.ayarlar.gunlukCalismaHedefiDk||180,hedefSoru=STATE.ayarlar.gunlukSoruHedefi||80,focus=Math.min(100,Math.round(dk/Math.max(1,hedefDk)*100)),achievements=Object.values(HUB.achievements).slice(-4).reverse();const old=page.querySelector('.study-hero');if(!old)return;const anchor=page.querySelector('.study-quick-grid');const box=document.createElement('div');box.className='focus-hub';box.innerHTML=`<div class="focus-hub-main"><div class="focus-hub-kicker">⚡ BUGÜNÜN ÇALIŞMA MASASI</div><div class="focus-hub-title">${focus>=100?'Günün hedefi tamamlandı. Şimdi pekiştir.':'Bir oturum daha. Sonra sonucu birlikte göreceğiz.'}</div><div class="focus-bars"><div><span>⏱️ Çalışma <b>${dk}/${hedefDk} dk</b></span><i><em style="width:${Math.min(100,dk/hedefDk*100)}%"></em></i></div><div><span>📝 Soru <b>${soru}/${hedefSoru}</b></span><i><em style="width:${Math.min(100,soru/hedefSoru*100)}%"></em></i></div></div><div class="focus-actions"><button class="btn btn-primary" id="hubFocusBtn">⏱️ Odak oturumu başlat</button><button class="btn btn-outline" id="hubReviewBtn">🔁 Akıllı tekrar (${review.length})</button></div></div><div class="focus-hub-side"><div class="hub-stat"><strong>🔥 ${streak()}</strong><span>gün seri</span></div><div class="hub-stat"><strong>🏆 ${Object.keys(HUB.achievements).length}</strong><span>başarı</span></div><div class="hub-stat"><strong>📚 ${topics.filter(k=>k.durum==='tamamlandi').length}</strong><span>konu bitti</span></div></div>`;anchor?.parentNode.insertBefore(box,anchor);box.querySelector('#hubFocusBtn')?.addEventListener('click',()=>openFocusModal());box.querySelector('#hubReviewBtn')?.addEventListener('click',openReviewModal);renderSmartPanels(page,weak,achievements);}
  function renderSmartPanels(page,weak,achievements){const wrap=document.createElement('div');wrap.className='smart-study-grid';const weakHtml=weak.length?weak.map(k=>`<button class="smart-topic" data-hub-ders="${esc(k.dersId)}" data-hub-id="${esc(k.id)}"><span class="smart-dot" style="background:${k.renk}"></span><span><b>${esc(k.ad)}</b><small>${esc(k.ders)} · %${yuzde(k.dogru||0,(k.dogru||0)+(k.yanlis||0))} başarı</small></span><strong>Çalış →</strong></button>`).join(''):`<div class="smart-empty">Henüz yeterli soru verisi yok. İlk 10–15 sorudan sonra sistem zayıf konuları yakalamaya başlayacak.</div>`;const ach=achievements.length?achievements.map(a=>`<div class="achievement"><span>🏆</span><div><b>${esc(a.label)}</b><small>${esc(a.date)}</small></div></div>`).join(''):`<div class="smart-empty">İlk başarını kazanmak için bir oturum başlat. 👊</div>`;wrap.innerHTML=`<section class="smart-panel"><div class="smart-panel-head"><div><h2>🎯 Zayıf Noktaların</h2><span>En çok puan kazandırabilecek konular</span></div></div>${weakHtml}</section><section class="smart-panel"><div class="smart-panel-head"><div><h2>🏆 Başarılar</h2><span>İlerledikçe açılır</span></div></div>${ach}</section>`;const toolbar=page.querySelector('.study-toolbar');toolbar?.parentNode.insertBefore(wrap,toolbar);wrap.querySelectorAll('[data-hub-id]').forEach(b=>b.addEventListener('click',()=>{if(typeof studyKonuAc==='function')studyKonuAc(b.dataset.hubDers,b.dataset.hubId)}));}
  function openReviewModal(){const list=reviewTopics().slice(0,8);modalAc('🔁 Akıllı Tekrar',`<div class="smart-modal-intro"><strong>Bugün en çok işine yarayacak tekrarlar</strong><p>Sistem yanlış oranı yüksek veya "tekrar gerekli" işaretlediğin konuları öne alıyor.</p></div><div class="review-list">${list.length?list.map((k,i)=>`<button class="review-item" data-review-ders="${esc(k.dersId)}" data-review-id="${esc(k.id)}"><span>${i+1}</span><div><b>${esc(k.ad)}</b><small>${esc(k.ders)} · ${k.soru||0} soru · %${yuzde(k.dogru||0,(k.dogru||0)+(k.yanlis||0))}</small></div><strong>Başla →</strong></button>`).join(''):'<div class="smart-empty">Şimdilik tekrar kuyruğun boş. Birkaç test çözdükten sonra otomatik oluşacak.</div>'}</div>`,`<button class="btn btn-primary" id="reviewClose">Tamam</button>`);document.querySelector('#reviewClose')?.addEventListener('click',modalKapat);document.querySelectorAll('[data-review-id]').forEach(b=>b.addEventListener('click',()=>{modalKapat();studyKonuAc(b.dataset.reviewDers,b.dataset.reviewId)}));}
  let timer={active:false,remaining:0,total:0,interval:null,topic:null};
  function openFocusModal(topic){const topics=allTopics().filter(k=>k.durum!=='tamamlandi');topic=topic||topics[Math.floor(Math.random()*Math.max(1,topics.length))];if(!topic)return toast('Önce bir konu ekleyelim.');const mins=Math.max(5,Number(HUB.focus.minutes)||25);timer.topic=topic;timer.remaining=mins*60;timer.total=mins*60;timer.active=false;modalAc('⏱️ Odak Oturumu',`<div class="focus-timer-wrap"><div class="focus-timer-mode">ODAKLAN · ${esc(topic.ders)}</div><div class="focus-timer" id="hubTimer">${fmt(timer.remaining)}</div><div class="focus-topic">📖 ${esc(topic.ad)}</div><div class="focus-timer-track"><i id="hubTimerBar"></i></div><p class="focus-timer-note">${mins} dakika sadece bu konu. Bildirimleri kapat, telefonu ters çevir, tek hedefe odaklan.</p></div>`,`<button class="btn btn-outline" id="hubTimerSkip">Bitir</button><button class="btn btn-primary" id="hubTimerToggle">▶ Başlat</button>`);document.querySelector('#hubTimerToggle')?.addEventListener('click',toggleTimer);document.querySelector('#hubTimerSkip')?.addEventListener('click',()=>finishTimer(false));}
  function fmt(s){return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;}
  function toggleTimer(){if(timer.active){timer.active=false;clearInterval(timer.interval);document.querySelector('#hubTimerToggle').textContent='▶ Devam';return}timer.active=true;document.querySelector('#hubTimerToggle').textContent='⏸ Duraklat';timer.interval=setInterval(()=>{timer.remaining--;updateTimer();if(timer.remaining<=0)finishTimer(true)},1000)}
  function updateTimer(){const el=document.querySelector('#hubTimer');if(el)el.textContent=fmt(Math.max(0,timer.remaining));const bar=document.querySelector('#hubTimerBar');if(bar)bar.style.width=`${Math.max(0,100-(timer.remaining/timer.total*100))}%`;}
  function finishTimer(completed){clearInterval(timer.interval);timer.active=false;const elapsed=Math.max(1,Math.round((timer.total-Math.max(0,timer.remaining))/60));if(elapsed>0){const k=studyKonuBul(timer.topic.dersId,timer.topic.id);if(k){k.calismaDk=(k.calismaDk||0)+elapsed;STATE.dersler[timer.topic.dersId].calismaDk=(STATE.dersler[timer.topic.dersId].calismaDk||0)+elapsed;const g=gunlukKayitAl();g.calismaDk=(g.calismaDk||0)+elapsed}STATE.calismaOturumlari=Array.isArray(STATE.calismaOturumlari)?STATE.calismaOturumlari:[];STATE.calismaOturumlari.push({id:Date.now().toString(36),tarih:today(),dersId:timer.topic.dersId,konuId:timer.topic.id,dakika:elapsed,tur:'odak'});stateKaydet();HUB.sessions.push({date:today(),minutes:elapsed,topic:timer.topic.ad});HUB.sessions=HUB.sessions.slice(-100);save();checkAchievements()}modalKapat();toast(completed?`🎉 ${elapsed} dakika tamamlandı!`:`${elapsed} dakikalık oturum kaydedildi.`);if(typeof renderCalisma==='function')renderCalisma();}
  function enhance(){if(typeof renderCalisma!=='function')return;if(renderCalisma.__hub)return;const original=renderCalisma;function wrapped(){original();renderHub()}wrapped.__hub=true;window.renderCalisma=wrapped;checkAchievements();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',enhance);else enhance();
})();
